feat: put test passing to pre-push, while pre-commit just warns about failing tests

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -8,4 +8,6 @@ if [[ -n $files ]]; then
     exit 1
 fi
 
-make test
+if ! make test 1>/dev/null 2>&1; then
+    echo "⚠️ WARNING: Tests failed but proceeding. Fix them before pushing!"
+fi
